#yzi.toml
[manager]
show_hidden = true

[opener]
pdf = [
	{ run = 'sioyek "$@"', desc = "Open PDF with sioyek" },
]
unzip = [
  { run = 'unar "$@"', desc = "Extract RAR with unar" },
]

[open]
rules = [
  { name = "*.pdf", use = "pdf"},
  { name = "*.rar", use = "unzip"},
  { name = "*.zip", use = "unzip"},
]
